services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,dynamodb,apigateway,sqs,sns
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./scripts/init.sh:/etc/localstack/init/ready.d/init.sh
      - "./lambda:/etc/localstack/init/ready.d/lambda"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_volume:/var/lib/localstack"

volumes:
  localstack_volume:
